name: StudioHiku
favicon: null
layout_spectrum: 1
typography_spectrum: 0.54928
title: StudioHiku
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d59d31'
    - '#748531'
    - '#c1612a'
    - '#25242a'
  brandStrength: 0.5
  lightness: 0.375
  saturation: 0.625
  rhythmicContrast: 1
purpose: []
